// ─── Quest Definitions ────────────────────────────────────────────────────────
const QUESTS = [
  {
    id: 'q-join',
    icon: '📍',
    title: 'First Steps',
    desc: 'Drop your pin on the map',
    xp: 0,
    auto: true,
  },
  {
    id: 'q-pioneer',
    icon: '🥇',
    title: 'Pioneer',
    desc: 'Be the first from your country',
    xp: 0,
    auto: true,
    condition: 'firstFromCountry',
  },
  {
    id: 'q-bridge',
    icon: '🌉',
    title: 'Bridge Builder',
    desc: 'Click a pin from a different continent',
    xp: 25,
    trigger: 'continents_1',
  },
  {
    id: 'q-ally',
    icon: '🤝',
    title: 'Value Ally',
    desc: 'Find someone who shares your leadership value',
    xp: 30,
    trigger: 'same_value',
  },
  {
    id: 'q-seeker',
    icon: '💬',
    title: 'Story Seeker',
    desc: 'Read 5 different cultural insights',
    xp: 40,
    trigger: 'insights_5',
  },
  {
    id: 'q-explorer',
    icon: '🌐',
    title: 'World Explorer',
    desc: 'Click pins from 3 different continents',
    xp: 50,
    trigger: 'continents_3',
  },
  {
    id: 'q-connector',
    icon: '🔗',
    title: 'Super Connector',
    desc: 'Click pins from 5 different countries',
    xp: 60,
    trigger: 'countries_5',
  },
];
