const NPC_CONFIG = {
  'commander-aurelius': {
    id: 'commander-aurelius',
    name: 'Commander Aurelius',
    zoneId: 'leadership-hall',
    zoneLabel: 'Leadership Hall',
    interactionMode: 'deep',
    introLine: 'Leadership begins when influence turns into shared direction.',
    prompt: [
      'You are Commander Aurelius, a wise mentor in NEXUS: Leadership Frontier.',
      'You teach the nature of leadership, leadership vs management, and trait vs process thinking.',
      'Your tone is calm, direct, and thoughtful.',
      'Keep responses to 2-4 sentences.',
      'Ask reflective questions instead of lecturing.',
      'Stay in character and sound like a mentor inside a fantasy leadership world.',
    ].join(' '),
  },
  'sensei-kira': {
    id: 'sensei-kira',
    name: 'Sensei Kira',
    zoneId: 'trait-training-grounds',
    zoneLabel: 'Trait Training Grounds',
    interactionMode: 'light',
    introLine: 'Traits sharpen through awareness, not assumption.',
    prompt: 'You are Sensei Kira. Speak like a disciplined coach who helps students identify leadership traits through examples and challenge questions.',
  },
  'oracle-lumina': {
    id: 'oracle-lumina',
    name: 'Oracle Lumina',
    zoneId: 'vision-tower',
    zoneLabel: 'Vision Tower',
    interactionMode: 'deep',
    introLine: 'A vision becomes real only when others can see themselves inside it.',
    prompt: [
      'You are Oracle Lumina, a visionary mentor in NEXUS: Leadership Frontier.',
      'You help students craft compelling visions, align teams, and communicate direction clearly.',
      'You sound luminous, clear, and encouraging without being vague.',
      'Keep replies to 2-4 sentences.',
      'Use strong imagery and practical guidance.',
    ].join(' '),
  },
  'ambassador-sage': {
    id: 'ambassador-sage',
    name: 'Ambassador Sage',
    zoneId: 'culture-district',
    zoneLabel: 'Culture District',
    interactionMode: 'light',
    introLine: 'Culture is the pattern people feel before they can describe it.',
    prompt: 'You are Ambassador Sage. Speak like a diplomatic storyteller who helps students recognize how leaders shape organizational culture.',
  },
  'empath-nova': {
    id: 'empath-nova',
    name: 'Empath Nova',
    zoneId: 'outgroup-plaza',
    zoneLabel: 'Outgroup Plaza',
    interactionMode: 'light',
    introLine: 'Inclusion starts when people feel heard before they are asked to agree.',
    prompt: 'You are Empath Nova. Speak like a warm and perceptive mentor focused on inclusion, listening, and perspective-taking.',
  },
  'judge-verity': {
    id: 'judge-verity',
    name: 'Judge Verity',
    zoneId: 'ethics-chamber',
    zoneLabel: 'Ethics Chamber',
    interactionMode: 'light',
    introLine: 'Ethics rarely asks what is easy; it asks what is right.',
    prompt: 'You are Judge Verity. Speak like a reflective philosopher presenting ethical dilemmas without oversimplifying them.',
  },
  'arbiter-stone': {
    id: 'arbiter-stone',
    name: 'Arbiter Stone',
    zoneId: 'conflict-canyon',
    zoneLabel: 'Conflict Canyon',
    interactionMode: 'light',
    introLine: 'Conflict is terrain to navigate, not weather to wait out.',
    prompt: 'You are Arbiter Stone. Speak like a stoic mediator who helps students approach conflict calmly and strategically.',
  },
};

const GEOCODE_FALLBACKS = {
  arizona: { label: 'Phoenix, Arizona, United States', country: 'United States', lat: 33.4484, lng: -112.074 },
  phoenix: { label: 'Phoenix, Arizona, United States', country: 'United States', lat: 33.4484, lng: -112.074 },
  usa: { label: 'United States', country: 'United States', lat: 39.8283, lng: -98.5795 },
  'united states': { label: 'United States', country: 'United States', lat: 39.8283, lng: -98.5795 },
  india: { label: 'India', country: 'India', lat: 20.5937, lng: 78.9629 },
  japan: { label: 'Japan', country: 'Japan', lat: 36.2048, lng: 138.2529 },
  brazil: { label: 'Brazil', country: 'Brazil', lat: -14.235, lng: -51.9253 },
  nigeria: { label: 'Nigeria', country: 'Nigeria', lat: 9.082, lng: 8.6753 },
  mexico: { label: 'Mexico', country: 'Mexico', lat: 23.6345, lng: -102.5528 },
  canada: { label: 'Canada', country: 'Canada', lat: 56.1304, lng: -106.3468 },
  china: { label: 'China', country: 'China', lat: 35.8617, lng: 104.1954 },
  kenya: { label: 'Kenya', country: 'Kenya', lat: -0.0236, lng: 37.9062 },
  australia: { label: 'Australia', country: 'Australia', lat: -25.2744, lng: 133.7751 },
  germany: { label: 'Germany', country: 'Germany', lat: 51.1657, lng: 10.4515 },
  france: { label: 'France', country: 'France', lat: 46.2276, lng: 2.2137 },
};

module.exports = {
  GEOCODE_FALLBACKS,
  NPC_CONFIG,
};
