import type { Archetype, NpcConfig, ZoneConfig } from './types';

export const ARCHETYPES: Archetype[] = [
  {
    id: 'visionary',
    label: 'The Visionary',
    accent: '#5BD37B',
    summary: 'Sees possibility early and turns direction into momentum.',
  },
  {
    id: 'collaborator',
    label: 'The Collaborator',
    accent: '#5CAAF2',
    summary: 'Builds alignment, inclusion, and forward motion through trust.',
  },
  {
    id: 'mediator',
    label: 'The Mediator',
    accent: '#F0A356',
    summary: 'Finds clarity inside difficult conversations and tense tradeoffs.',
  },
  {
    id: 'innovator',
    label: 'The Innovator',
    accent: '#CC6BEB',
    summary: 'Moves through obstacles creatively and reframes what is possible.',
  },
];

export const ZONES: ZoneConfig[] = [
  {
    id: 'leadership-hall',
    label: 'Leadership Hall',
    moduleTitle: 'Module 1 — The Nature of Leadership',
    worldPosition: [0, 0, -25],
    color: '#FFD166',
    accent: '#E3A14D',
    ambientPreset: 'gold',
    npcId: 'commander-aurelius',
    depth: 'deep',
    recommendedOrder: 1,
    intro: 'The foundational chamber where leadership is defined, debated, and tested.',
    interactionHook: 'Compare leadership to management and challenge the meaning of influence.',
  },
  {
    id: 'trait-training-grounds',
    label: 'Trait Training Grounds',
    moduleTitle: 'Module 2 — Recognizing Leadership Traits',
    worldPosition: [18, 0, -15],
    color: '#FF6B6B',
    accent: '#FF8A5B',
    ambientPreset: 'ember',
    npcId: 'sensei-kira',
    depth: 'light',
    recommendedOrder: 2,
    intro: 'An arena of standing stones where leadership traits are revealed through challenge.',
    interactionHook: 'Identify which traits strengthen leadership and where they cast shadows.',
  },
  {
    id: 'vision-tower',
    label: 'Vision Tower',
    moduleTitle: 'Module 3 — Creating a Vision',
    worldPosition: [25, 0, 2],
    color: '#51CF66',
    accent: '#9EF29D',
    ambientPreset: 'verdant',
    npcId: 'oracle-lumina',
    depth: 'deep',
    recommendedOrder: 3,
    intro: 'A radiant tower where a leader learns to articulate a future others can join.',
    interactionHook: 'Craft a compelling direction and test it against doubt.',
  },
  {
    id: 'culture-district',
    label: 'Culture District',
    moduleTitle: 'Module 4 — Setting the Tone',
    worldPosition: [18, 0, 20],
    color: '#4DABF7',
    accent: '#7FC8FF',
    ambientPreset: 'azure',
    npcId: 'ambassador-sage',
    depth: 'light',
    recommendedOrder: 4,
    intro: 'Interlinked structures where every choice shapes the climate people inhabit.',
    interactionHook: 'Read what a team feels before it can say it aloud.',
  },
  {
    id: 'outgroup-plaza',
    label: 'Outgroup Plaza',
    moduleTitle: 'Module 5 — Inclusion and Out-Groups',
    worldPosition: [-2, 0, 27],
    color: '#CC5DE8',
    accent: '#E2A7FF',
    ambientPreset: 'violet',
    npcId: 'empath-nova',
    depth: 'light',
    recommendedOrder: 5,
    intro: 'A ringed civic space where distance and belonging are made visible.',
    interactionHook: 'Listen for voices that leadership usually hears too late.',
  },
  {
    id: 'ethics-chamber',
    label: 'Ethics Chamber',
    moduleTitle: 'Module 6 — Ethics in Leadership',
    worldPosition: [-20, 0, 18],
    color: '#20C997',
    accent: '#7CF0D0',
    ambientPreset: 'teal',
    npcId: 'judge-verity',
    depth: 'light',
    recommendedOrder: 6,
    intro: 'A transparent hall of judgment where decisions are measured from multiple angles.',
    interactionHook: 'Test whether the right choice still feels right under pressure.',
  },
  {
    id: 'conflict-canyon',
    label: 'Conflict Canyon',
    moduleTitle: 'Module 7 — Conflict and Obstacles',
    worldPosition: [-25, 0, -2],
    color: '#FF922B',
    accent: '#FFD08A',
    ambientPreset: 'cinder',
    npcId: 'arbiter-stone',
    depth: 'light',
    recommendedOrder: 7,
    intro: 'A fractured landscape where leaders learn to move through tension instead of around it.',
    interactionHook: 'Navigate disagreement, pressure, and unstable terrain without losing the team.',
  },
];

export const NPCS: NpcConfig[] = [
  {
    id: 'commander-aurelius',
    name: 'Commander Aurelius',
    zoneId: 'leadership-hall',
    characterAssetId: 'lara-prototype',
    promptKey: 'commander-aurelius',
    introLine: 'Leadership begins where influence becomes shared purpose.',
    interactionMode: 'deep',
    interactionRadius: 4.4,
  },
  {
    id: 'sensei-kira',
    name: 'Sensei Kira',
    zoneId: 'trait-training-grounds',
    characterAssetId: 'lara-prototype',
    promptKey: 'sensei-kira',
    introLine: 'Traits reveal themselves through patterns, not labels.',
    interactionMode: 'light',
    interactionRadius: 4.2,
  },
  {
    id: 'oracle-lumina',
    name: 'Oracle Lumina',
    zoneId: 'vision-tower',
    characterAssetId: 'lara-prototype',
    promptKey: 'oracle-lumina',
    introLine: 'A vision is strongest when others can see themselves inside it.',
    interactionMode: 'deep',
    interactionRadius: 4.5,
  },
  {
    id: 'ambassador-sage',
    name: 'Ambassador Sage',
    zoneId: 'culture-district',
    characterAssetId: 'lara-prototype',
    promptKey: 'ambassador-sage',
    introLine: 'Culture is what people learn from the room before they hear the speech.',
    interactionMode: 'light',
    interactionRadius: 4.1,
  },
  {
    id: 'empath-nova',
    name: 'Empath Nova',
    zoneId: 'outgroup-plaza',
    characterAssetId: 'lara-prototype',
    promptKey: 'empath-nova',
    introLine: 'Inclusion starts where listening becomes action.',
    interactionMode: 'light',
    interactionRadius: 4.1,
  },
  {
    id: 'judge-verity',
    name: 'Judge Verity',
    zoneId: 'ethics-chamber',
    characterAssetId: 'lara-prototype',
    promptKey: 'judge-verity',
    introLine: 'Ethics asks what remains right when comfort disappears.',
    interactionMode: 'light',
    interactionRadius: 4.2,
  },
  {
    id: 'arbiter-stone',
    name: 'Arbiter Stone',
    zoneId: 'conflict-canyon',
    characterAssetId: 'lara-prototype',
    promptKey: 'arbiter-stone',
    introLine: 'Conflict is terrain to cross with care, not a storm to outwait.',
    interactionMode: 'light',
    interactionRadius: 4.4,
  },
];
